### ISSUE TITLE
Multi-instance disappear when we use a template

### ISSUE THREAD

**Issue by pierre-yves-monnet** [bpmn-io/bpmn-js-properties-panel#907] opened 2023-04-18 19:21 UTC
### Describe the Bug

When I add a "multi-instance" on a service task with a template, then the "multi-instance" option disappears from the properties...

### Steps to Reproduce

1. Add a service task
2. Click on the Wrench, select the "Sequential multi-instance" option 
3. Check the properties: you see an option "multi-instance"
4. Select a template
5. Check the properties: option "multi-instance" disappeared

### Expected Behavior

The option "multi-instance" is still here

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]:  desktop modeler 5.10.0
- OS: [e.g. Windows 7] Windows 10
- Library version: [e.g. 2.0.0] Desktop modeler 5.10.11

**Comment by nikku** [comment] 2023-04-25 08:01
Thanks for reporting this issue. This seems to be a duplicate of https://github.com/camunda/camunda-modeler/issues/3396.

**Comment by nikku** [comment] 2023-04-25 08:02
Actually not a duplicate, but the upstream issue for https://github.com/camunda/camunda-modeler/issues/3396. Moving to backlog for the time being.

**Comment by nikku** [comment] 2023-10-17 19:44
Closing this in favor of downstream issue: https://github.com/camunda/camunda-modeler/issues/3396.

**Closed by nikku** 2023-10-17 19:44 UTC
Labels: bug, ready, element templates
