### ISSUE TITLE
TextBoxEntry is still editable after disable it with [propertiesPanel.isPropertyEditable] event

### ISSUE THREAD

**Issue by maurrysonn** [bpmn-io/bpmn-js-properties-panel#472] opened 2021-06-01 14:08 UTC
__Describe the Bug__

I disable many fields with `propertiesPanel.isPropertyEditable` event and, after that, the _process name_ field (witch is an `TextBoxEntry`) is still editable.

![camunda-name-textbox](https://user-images.githubusercontent.com/1659827/120336400-999cdb00-c2f2-11eb-9e58-8e13c938638c.png)

The corresponding div element seems ok and contains `readonly` and `disabled` attributes, like others `TextFieldEntry` for example.

![camunda-name-div](https://user-images.githubusercontent.com/1659827/120335467-c7cdeb00-c2f1-11eb-984e-6e1dac734a42.png)

I think there is a conflict with `contenteditable` attribute because after remove it, all is fine.

**Important** : field modifications are not saved in the model, so the field is really `readonly` field. The problem is just about HTML rendering.

__Steps to Reproduce__

1. Add event listener on `propertiesPanel.isPropertyEditable`
2. Return `false` for _process name_ field
3. _Process Name_ field is still editable

Reproducible inside this [CodeSandbox](https://codesandbox.io/s/propertiespanel-disable-processname-ulz1h?file=/src/index.js).

__Expected Behavior__

The _process name_ field should not be editable.

__Environment__

- Host Firefox 89.0
- OS: Windows 10
- Library version: 0.43.0

**Comment by pinussilvestrus** [comment] 2021-06-04 08:15
Thanks for reporting! Are you maybe able to share your code where you disable these fields inside a [CodeSandbox](https://codesandbox.io/s/zealous-shtern-9kv6q)? This way it would be much easier for us to reproduce the issue.

**Comment by maurrysonn** [comment] 2021-06-07 07:51
Hi Niklas, I updated the code in CodeSandbox (at the bottom of index.js).

**Comment by pinussilvestrus** [comment] 2021-06-07 15:08
Which one do you mean? [This one](https://codesandbox.io/s/zealous-shtern-9kv6q)? Did you save the changes? Sometimes it's not doing it automatically (indicated by the dirty state indicator).

**Comment by maurrysonn** [comment] 2021-06-08 06:51
Ooops... sorry ! I think I created a new Sandbox when I had new dependency... : [The Good One](https://codesandbox.io/s/modest-wu-1dstv?file=/src/index.js) ! 😄

**Comment by pinussilvestrus** [comment] 2021-06-08 06:59
Thanks for sharing! I was able to reproduce it when [disabling the `processName` field](https://codesandbox.io/s/propertiespanel-disable-processname-ulz1h?file=/src/index.js). Really seems like the `disabled` state is not properly working with this attribute.

**Comment by barmac** [comment] 2022-04-13 12:41
I am closing this as `wontfix` because we released a complete rewrite of the properties panel as v1.0.0. Please feel free to reopen this issue if the problem persists in the 1.x series.

**Closed by barmac** 2022-04-13 12:41 UTC
Labels: bug, backlog, 0.x
