### ISSUE TITLE
After bump to bpmn-js@9, prop panel state does not update anymore

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-js-properties-panel#569] opened 2022-02-07 10:19 UTC
__Describe the Bug__

After bump to bpmn-js@9, prop panel state does not update anymore on root / process level

__Steps to Reproduce__

1. Checkout https://github.com/bpmn-io/bpmn-js-properties-panel/commit/2ffd7701288db3067602c6a7bb4fceef721d592e
2. Run `npm run start:platform`
3. Try to add list items on root level (e.g., process selected)
4. See that state does not update:

![noStateUpdate](https://user-images.githubusercontent.com/42800119/152769298-6df8f414-9cc5-473c-b41d-ed191e6e314a.gif)

__Expected Behavior__

State does update

__Environment__

- Host (Browser/Node version), if applicable: Chromium / Brave
- OS: Linux
- Library version: https://github.com/bpmn-io/bpmn-js-properties-panel/commit/2ffd7701288db3067602c6a7bb4fceef721d592e

**Comment by pinussilvestrus** [comment] 2022-02-07 10:35
Whoops

![image](https://user-images.githubusercontent.com/9433996/152771930-bef4bbfc-cc59-47ea-a82a-e494c0f3dd6d.png)

**Comment by marstamm** [comment] 2022-02-07 10:38
I can reproduce this. Root cause is in bpmn-js:

https://github.com/bpmn-io/bpmn-js/blob/fb6c6495701e693e76c89d97cf05d96a0c7e5c35/lib/features/drilldown/DrilldownBreadcrumbs.js#L41

We do not check if it is a sub-process, so we create an infinite loop if we change the root :sweat_smile:

**Comment by MaxTru** [comment] 2022-02-10 07:44
would this not be fixed upstream now (since https://github.com/bpmn-io/bpmn-js/pull/1593 was merged)? @marstamm

**Comment by marstamm** [comment] 2022-02-10 07:46
Actually, it is already closed via af6c5a610bbe94e320dd22a31031c6859a79a6b6

Thanks for reminding me @MaxTru

**Comment by MaxTru** [comment] 2022-02-10 07:46
That is even better of course :-)

**Closed by marstamm** 2022-02-10 07:46 UTC
Labels: bug, in progress
