### ISSUE TITLE
Loop Cardinality Error

### ISSUE THREAD

**Issue by NPDeehan** [bpmn-io/bpmn-js-properties-panel#107] opened 2015-12-10 12:45 UTC
When creating a multi-instance that loops using the loop cardinality. An "element variable" is created in the XML. This is only used for looping collections and will throw an error when deploying to the platform.

      <bpmn:multiInstanceLoopCharacteristics camunda:elementVariable="undefined">
        <bpmn:loopCardinality xsi:type="bpmn:tFormalExpression">6</bpmn:loopCardinality>
      </bpmn:multiInstanceLoopCharacteristics>

**Comment by shentschel** [comment] 2015-12-11 11:40
Hi Niall.

This is a bug in the camunda-bpmn-moddle project. I created a bug there: https://github.com/camunda/camunda-bpmn-moddle/issues/22

I will also close this ticket because it is not a bug in the properties panel.

Cheers,

Stefan :)

**Closed** 2015-12-11 11:40 UTC
Labels: bug
