### ISSUE TITLE
I have also encountered the same problem. Have you solved it? This issue occurred in version 0.46

### ISSUE THREAD

**Issue by 52Tiantian** [bpmn-io/bpmn-js-properties-panel#1075] opened 2024-08-22 02:17 UTC
I have also encountered the same problem. Have you solved it? This issue occurred in version 0.46

_Originally posted by @52Tiantian in https://github.com/bpmn-io/bpmn-js-properties-panel/issues/951#issuecomment-2303519742_

**Comment by nikku** [comment] 2024-08-22 08:54
@52Tiantian I believe you'll not get a better answer by opening this in another issue. `v0.46` is a bunch of years out of maintainance, if you want things fixed in this ancient version then we rely on you and/or the community.

**Comment by nikku** [comment] 2024-08-22 08:55
Closed as duplicate of https://github.com/bpmn-io/bpmn-js-properties-panel/issues/951.

**Closed by nikku** 2024-08-22 08:54 UTC
