### ISSUE TITLE
how to use it without node.js?

### ISSUE THREAD

**Issue by polarloves** [bpmn-io/bpmn-js-properties-panel#269] opened 2018-07-09 06:46 UTC
hello
how can i use it without node.js?
i know bpmn-js provided pre compile version,i got it and worked well,but this plugin,i don't know how to use it.
pls,tks

### Steps to reproduce the Behavior

**Comment by daveleenew** [comment] 2018-07-09 07:58
@polarloves hello  ,would you send the bpmn-js pre compile version link to me ? thanks

**Comment by polarloves** [comment] 2018-07-09 08:00
https://unpkg.com/bpmn-js@2.3.1/dist/

**Comment by daveleenew** [comment] 2018-07-09 08:38
@polarloves thanks

**Comment by nikku** [comment] 2018-07-09 09:17
We don't offer a pre-packaged properties panel at the moment.

Please refer to [this example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel) how to combine and bundle the properties panel together with the modeler.

Closing this issue as a duplicate of https://github.com/bpmn-io/bpmn-js-properties-panel/issues/270.

**Closed by nikku** 2018-07-09 09:17 UTC
