### ISSUE TITLE
The undo stack inserts deleted content in the wrong flow nodes

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/bpmn-js-properties-panel#712] opened 2022-06-28 20:18 UTC
__Describe the Bug__

When you delete a name or id of a flow node in the properties panel, then add a new node and hit undo, the name or id is inserted back again - in the right property, but of the wrong flow node. So, the revert operation is not conducted properly. Also, adding the flow node itself is not reverted. It seems like the undo stacks of the properties panel and bpmn-js clash.

__Steps to Reproduce__

1. Have a flow node
2. Enter a name or id
3. Remove the name or id (select all + entf/backspace/cut)
4. Add a new flow node
5. Hit undo
6. -> The name or id is inserted back again, but in the currently selected flow node (the new one) 

Or just see the videos.

https://user-images.githubusercontent.com/56470362/176275701-3d262892-2b27-4144-8180-f7742ac909cb.mov

https://user-images.githubusercontent.com/56470362/176275720-1f74548e-499e-427f-a39c-4707f34d1b8a.mov

(Not validated if this also applies to other properties than ids and names).

__Expected Behavior__

Hitting undo, at first the newly added flow node should be removed, then the name or id should be inserted back again in the original node.

__Environment__

- Desktop Modeler 5.0.0 and Web Modeler (Nightly and our current dev env ultrawombat)

**Comment by pinussilvestrus** [comment] 2022-07-19 11:53
Seems like this is related to direct editing visible after creating/appending tasks and text annotations. 

![Kapture 2022-07-19 at 13 49 54](https://user-images.githubusercontent.com/9433996/179743718-4535d077-f103-4700-95eb-2edbf572082d.gif)

I can't reproduce it if I append a flow node that's not immediately activating direct editing.

![Kapture 2022-07-19 at 13 51 19](https://user-images.githubusercontent.com/9433996/179743661-703c42e1-eb16-4d73-a253-f6208f7ca6a9.gif)

**Comment by pinussilvestrus** [comment] 2022-07-19 12:58
I looked through the commit history to find a point where it is working properly. The bug even occurs in [version `1.0.0-alpha.0`](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/CHANGELOG.md#100-alpha0).

I was not able to find the root cause for this in a time-boxed manner. However, I created a test case via https://github.com/bpmn-io/bpmn-js-properties-panel/commit/0dcd373883a03c109f1312265cb01987c9409e7b that tries to reproduce the issue.

What I found while creating the test case:
* The test case is failing randomly because the name input sometimes has focus. It shouldn't be like that after append, as direct editing is activated. Sometimes it just works as expected.
* When doing the same by firing command via `commandStack` only, everything works as expected.

This could be an indication that something is going on with handling the keyboard bindings + focusing properly between the modeler and properties panel.

I'd need more time to investigate this, so I'd propose to move this to backlog as it's not a blocker.

**Comment by marstamm** [comment] 2022-08-17 08:29
> **Expected Behavior**
>
> Hitting undo, at first the newly added flow node should be removed, then the name or id should be inserted back again in the original node.

As we are in the context of direct editing, undo should not be handled by bpmn-js at all but perform the native undo/redo on the contenteditable div

**Comment by nikku** [comment] 2022-08-17 08:39
Could this be another one to be fixed by https://github.com/bpmn-io/diagram-js/pull/662?

**Comment by marstamm** [comment] 2022-08-17 08:44
I will try it out with your branch (https://github.com/bpmn-io/bpmn-js-properties-panel/pull/739), but I am not confident that it will be solved. No actual undo is triggered currently. I suspect it has more to do with focus handling/Event listeners during re-render of the property panel

**Comment by marstamm** [comment] 2022-08-17 08:52
I can still reproduce it on #739

**Comment by nikku** [comment] 2022-08-17 09:00
You'd need to test it against an end-to-end setup scenario: https://github.com/bpmn-io/diagram-js/pull/662#issuecomment-1216708578. There are just too many moving parts at the moment :smile:

**Comment by marstamm** [comment] 2022-08-17 09:16
I did locally link the diagram and bpmn-js branches as well 😄 
It is releavant that we have the Properties panel, I found the root cause and it is not something we can handle in bpmn-js.

**Root Cause**
- When you have 2 inputs and use the browser-native undo, it will switch the focused element.
![Recording 2022-08-17 at 11 04 59](https://user-images.githubusercontent.com/21984219/185080030-2e55e80b-7e31-4f21-92e2-58f988363bc9.gif)
- Usually, we capture the keyDown events and handle undo/redo ourselves
- DirectEditing does not have the custom key handlers, a `historyUndo` InputEvent is created. This is a normal input event and is not captured by keyHandlers
- We reuse the input field for names and only change the value. This causes focus to be set and the value to be changed by the input event

**Possible Solutions** 
Still thinking about these ones. As the expected behaviour would be to stay in direct editing, I think we should prevent the browser default there.

**Comment by marstamm** [comment] 2022-08-17 11:29
Same case can be created with undo via context pad, so the fix needs to be in the properties panel. 
![Recording 2022-08-17 at 13 20 35](https://user-images.githubusercontent.com/21984219/185107503-5feacc21-1233-46fe-a824-b225cd902e1a.gif)

I'll see if we can capture `undoHistory` events in the root before they reach the target and execute a commandstack undo instead

**Comment by nikku** [comment] 2022-08-17 12:06
Given your analysis I believe we should simply make sure that input (task A) is different from input (task B) (via a `key` attribute). 

If we do that though we'll run into the issue that we don't properly remember (and restore) collapse + expand states.

**Comment by marstamm** [comment] 2022-08-17 12:15
I was trying to use the `beforeinput` event to trigger commandstack undo when attempting to undo, but the `beforeinput` event is triggered on the direct editing container, the following `input` event in the properties panel.

> Given your analysis I believe we should simply make sure that input (task A) is different from input (task B) (via a key attribute).

That makes sense. I'll try it out.
I have not looked at the collapse/expand states yet. From my understanding, if we only replace the inputs, the group should stay the same and could keep the collapse/expand state.

**Comment by nikku** [comment] 2022-08-17 12:17
> From my understanding, if we only replace the inputs, the group should stay the same and could keep the collapse/expand state.

Yes, however it will have other unwanted side-effects. I.e. caching of state fetched for Task A and making it available for Task B.

I'm fine though to address / investigate this some day in the future.

**Closed** 2022-08-19 13:05 UTC
Labels: bug, spring cleaning, fixed upstream
