### ISSUE TITLE
Some section headers are mistakenly rendered as sticky (with the wrong background color)

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/bpmn-js-properties-panel#726] opened 2022-07-11 17:08 UTC
__Describe the Bug__

Some sections appear in the wrong background color. This happens often, and randomly. It seems that the sticky heading detection goes wrong here (see the CSS class in below screenshot).

![Bildschirmfoto 2022-07-11 um 19 08 45](https://user-images.githubusercontent.com/56470362/178319656-613fc67d-3324-4099-a6fc-4ae9693777da.png)

__Steps to Reproduce__

1. Select a service task
2. Play around with the properties panel
3. Some headers are gray, some are white when expanded

See the screencast:

https://user-images.githubusercontent.com/56470362/178319431-f9670f27-2da3-4a98-a4f6-646bfbac9b9d.mov

Another bad example which also renders the list margins broken:

![Bildschirmfoto 2022-07-11 um 19 09 28](https://user-images.githubusercontent.com/56470362/178319804-e1ff17c7-9c0c-4e38-b3d3-15cc89a6b44e.png)

__Expected Behavior__

Only sticky headers should be gray.

__Environment__

- Desktop Modeler 5.1.0-rc1
- OS: MacOS Monterey

**Comment by pinussilvestrus** [comment] 2022-07-15 07:20
Context: the [`sticky` observer ](https://github.com/bpmn-io/properties-panel/blob/main/src/hooks/useStickyIntersectionObserver.js) is sometimes setting the class incorrectly, calculating a `intersectionRatio` below 1 although when that's not the case.

**Comment by pinussilvestrus** [comment] 2022-07-28 08:36
After chatting with @Skaiir we decided to not invest more time into this, as it's not easy to find out where the wrong intersection calculations come from (cf. https://github.com/bpmn-io/bpmn-js-properties-panel/issues/726#issuecomment-1185254665).

I'd propose to toggle the sticky headers off completely until we find a proper fix for this. I think [monkey patching the styles](https://github.com/camunda/camunda-modeler/pull/3026) on product level does not help, as the feature is not working reliable in other scenarios as well - I was able to reproduce it via `npm run start:platform` as well.

I created a PR for that in the properties panel framework: https://github.com/bpmn-io/properties-panel/pull/172. Once we find a proper fix, we can remove this feature guard.

**Comment by marstamm** [comment] 2022-08-16 12:06
Short update on what I found so far:

- The wrong calculation in the IntersectionObserver happens when we switch selection between elements
- It's only specific groups that I can replicate it with (in C7: Execution Listeners, Extension properties, External Task) 
- The Observer is called with both the entry and container boundingClientRect set to `{"x":0,"y":0,"width":0,"height":0,"top":0,"right":0,"bottom":0,"left":0}`

I believe the calculation goes wrong during the rerender of the properties panel and also depeneds on how the specific property groups are mounted. E.g., "External Task" is a conditional group, so it might not be mounted right at the re-render. I'll dig deeper into it

**Comment by marstamm** [comment] 2022-08-16 12:21
I am able to replicate it consistently:

![Recording 2022-08-16 at 14 19 20](https://user-images.githubusercontent.com/21984219/184878094-d2d4684f-7c12-4870-9170-e0f777f4c3ec.gif)

1. The Elements (A, B) share some common groups
2. A has one or more additional groups (in the screencast: External Task + Errors)
3. I switch from Task A to Task B
4. All groups below the removed group(s) are marked sticky, except for newly created groups

**Comment by marstamm** [comment] 2022-08-16 13:14
Fixed it! 👷 

[`entries`](https://github.com/bpmn-io/properties-panel/blob/598929fd94a8300b2db436e715999a36bb91d4fe/src/hooks/useStickyIntersectionObserver.js#L45) is an array, we only use the first event.

During the re-render, the DOM element gets unmounted and re-inserted at another postion into the DOM. Because the callback bundles events since the last callback, `entries` now has 2 entries, `[0]` is unmount, `[1]` is remount. Because we only handle `[0]`, we never set `sticky` back to false.

**Closed** 2022-08-19 13:05 UTC
Labels: bug, spring cleaning, fixed upstream
